# Generated by Django 4.0.2 on 2022-02-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rightAnswer',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
